version: '3.7'

services:
  cassandra_3_11_4:
    image: "cassandra:3.11.4"
    ports:
      - "9042:9042"
    expose:
      - "9042"
    volumes:
      - ./volumes/cassandra/3.11.4:/var/lib/cassandra
